# Generated by Django 4.2 on 2024-08-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_withdrawalrequest_pocketmoney_jobreport_jobcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='pocketmoney',
            name='aproved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
